### ISSUE TITLE
Clarify iptstate situation

### ISSUE THREAD

**Issue by mika** [grml/grml-live#108]
iptstate is gone from Debian/testing since 2021-10-14 due to https://bugs.debian.org/994193. I pinged the maintainer twice in the meanwhile but didn't get any feedback. It's preventing Debian/testing based daily Grml builds, so at least for the time being let's drop it.

Should be clarified for upcoming stable Grml release how to be handled.

**Comment by zeha** [comment]
I've NMUed iptstate, so it should show up in testing in a week or so.
