### ISSUE TITLE
Replace memtest86+ with pcmemtest?

### ISSUE THREAD

**Issue by mika** [grml/grml-live#109]
memtest86+ doesn't support EFI boot, while https://github.com/martinwhitaker/pcmemtest claims to provide EFI support, though pcmtest is available in Debian testing + unstable only for now, though that might be worth giving it a try.

**Comment by riesebie** [comment]
:+1:  :shipit:

**Comment by evgeni** [comment]
Do we need to *replace*?

Can't we hide m86+ on UEFI and show both on BIOS boot?

Reason being twofold:
* Memory testing always was a bit religious, and we could try to offer whatever people prefer
* M86+ might get UEFI support in the future

**Comment by evgeni** [comment]
And just like this, https://github.com/memtest86plus/memtest86plus happened, which is now "Memtest86+ v6.0 was based on PCMemTest, which was a fork and rewrite of the earlier Memtest86+ v5.01, which in turn was a fork of Memtest86." :exploding_head:

**Comment by zeha** [comment]
memtest86 in experimental is already the pcmemtest variant. So its likely nothing needs to be done :-)
