### ISSUE TITLE
Load to RAM not working when using grml64-small_2021.07.iso

### ISSUE THREAD

**Issue by ironiq** [grml/grml-live#113]
When i would like to boot the GRML64 small iso with the option "Load to RAM", i get the error "run-init: can't execute '/sbin/init': No such file or directory" after "Begin: Running /scripts/init-bottom ... done." All others before this seem to be good, no other error given. The normal boot method works, other methods were not tried.

The screenshot below is from VMware, but the same error is provided when booting from USB pendrive attached to a physical machine.

Screenshot of the error:
![grml64-small-2021_07-loadtoram-error](https://user-images.githubusercontent.com/639399/170500529-dcd1f64c-3c79-4ffc-a457-2c48156b9395.png)

**Comment by ironiq** [comment]
In isolinux the cmdline contains: "toram=%SQUASHFS_NAME%". I think the problem will be around here. I will check it deeper.

**Comment by mika** [comment]
Thanks for reporting, this is a known issue (see https://grml.org/bugs/known/), and was already reported as https://github.com/grml/grml/issues/179 and fixed via https://github.com/grml/grml-live/commit/48c20386e11d2cb70b23ef8a6024d6f8c7d6720a :)
