### ISSUE TITLE
adduser 3.122 breaks addgroup behavior

### ISSUE THREAD

**Issue by mika** [grml/grml-live#115]
Daily Grml ISO builds fail due to:

```
=====   shell: GRMLBASE/21-usersetup   =====
Adding group `grml' (GID 1000) ...
Done.
addgroup: addgroup with two arguments is an unspecified operation.
GRMLBASE/21-usersetup FAILED with exit code 1.
```

Seems to be caused by new behavior of adduser 3.122 as present in Debian testing/unstable (see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=664869).

**Comment by zeha** [comment]
maybe ask marc to revert this. he wanted feedback on the new release anyway
