### ISSUE TITLE
lsb-base-logging.sh issue

### ISSUE THREAD

**Issue by R-Sommer** [grml/grml-live#125]
Booting from Grml 2022.11 and running grml-live result in:

```
/etc/lsb-base-logging.sh: line 19: -S: command not found
/etc/lsb-base-logging.sh: line 19: -S: command not found
[  OK  ] Sourcing configuration file /etc/grml/grml-live.conf

grml-live [0.42.2]: check your configuration (or use -F to force execution):
...
```

**Comment by mika** [comment]
@R-Sommer something™ seems to rely on `/etc/lsb-base-logging.sh` which is incompatible of our (Grml) lsb-functions, I've seen something like this already with other software, that's something we need to fix. Thanks for reporting!
