### ISSUE TITLE
default serial speed to 115200

### ISSUE THREAD

**Issue by anarcat** [grml/grml-live#130]
Long gone are the days where the 9600 baud rate was canonical. Nowadays, you mostly find 115200 out there. As an example out there, the PC Engines "Alix" series was using the 9600 baud rate but their newer "APU" series use 115200. The APU series have been around for years already, to finalize that reference point.

I'm not exactly sure where that should be changed, but from a user's perspective, the "Serial console" menu currently passes console=ttyS0,9600n8 to the kernel, and that would be a good place to start. At least having that option in the boot menu would improve things, as it's sometimes quite impractical to edit that commandline if you happen to run a somewhat exotic terminal emulator (in my case, the de-facto Wayland standard, foot).

**Comment by mika** [comment]
@anarcat good idea, thanks! New grml-live version should take care of this :)

**Comment by anarcat** [comment]
excellent! for what it's worth, i tried grepping around for the value but couldn't find the right config file... thanks!
