### ISSUE TITLE
Include f3 package

### ISSUE THREAD

**Issue by ki9us** [grml/grml-live#134]
[f3, Fight Flash Fraud](https://github.com/AltraMayor/f3) is a utility to quickly verify that drives aren't fake.  These fake capacity-reporting drives are becoming prolific online so I run `f3probe` on drives as part of my diagnostic routine.  

I don't know any diagnostic boot disks that come with f3 so usually I boot into grml and run `sudo apt update; sudo apt install f3`.  This requires internet of course so it'd be handy if f3 was included in grml.  It's already in the apt repos and I don't think it's very big.

**Comment by mika** [comment]
@ki9us this is a great idea, added it to the software list of grml-full, so the daily ISOs as of tomorrow as well as upcoming stable releases should include it, thx!
