### ISSUE TITLE
does it support easily creating live system from ubuntu also

### ISSUE THREAD

**Issue by zaxebo1** [grml/grml-live#16]
My aim was to find a tool to create customised debian and ubuntu based live CD environments from the same method. From the manual I see that grml can generate live system from debian. 
Can it also generate live system from ubuntu **easily** in the same way

**Comment by mika** [comment]
You write `create customised debian and ubuntu based live CD environments` and `generate live system from ubuntu`, which are two different things.

1) grml-live does NOT build Ubuntu based live systems, it builds Debian based live environments. (Though technically it *should* be possible to build Ubuntu based systems as well, but I personally don't have that requirement and demand for it wasn't really visible so far.)

2) You *should* be able to use grml-live *from* Ubuntu to build Debian based live environments though, if you use the Debian packages we provide. grml-live depends on:

````
bc, bzip2, fai-client (>= 3.4.0), fai-server (>= 3.4.0), memtest86+, mksh, moreutils,
pciutils, rsync, squashfs-tools (>= 1:4.2-0~bpo60), syslinux, xorriso | genisoimage
````

The fai-client, fai-server and moreutils packages are available from Ubuntu universe, all the rest seems to be available straight out from Ubuntu precise/trusty/vivid/wily main. I personally don't run grml-live on Ubuntu, but if you should experience any issues with that please just report any problems you should run into.
