### ISSUE TITLE
update debian style secure boot

### ISSUE THREAD

**Issue by pasja** [grml/grml-live#168]
Dear @mika,

In the spirit of #129 please pull the latest grub (1+2.12+5) and shim (1.44) from trixie. 
Currently grml is unbootable on secure boot enabled and dual-booting machines due to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1078956

I have applied the corresponding files from the packages on my machine and had a successful secure boot with them 😃

Thanks in advance!

Regards,
János Pásztor

**Comment by zeha** [comment]
It occurred to me this was going to be necessary. Maybe we can also drop some of the files. I guess the old ubuntu shim/grub also wont work anymore.

**Comment by mika** [comment]
Thanks for raising this, @pasja - just took care of it!

PS: thanks also for the lovely post card, we love it! :)
