### ISSUE TITLE
EFI / Grub: error message in sub menu entry

### ISSUE THREAD

**Issue by zeha** [grml/grml-live#209]
<img width="912" alt="Image" src="https://github.com/user-attachments/assets/f84c8419-654d-498e-9da6-10849c6f8c10" />

After pressing a key it boots, but this shouldn't happen.
amd64 is fine.

I'm also wondering if the console=... option is even correct for arm64.

**Comment by zeha** [comment]
The error message from grub happens for all options in the Options menu.

**Comment by jkirk** [comment]
The error message is shown when selecting _any_ sub menu entry under "Options".

Taking over from my duplicate issue grml/grml#214:

**Describe the bug**
Booting Grml in EFI mode brings the new Grub  boot theme (see: grml/grml-live@b0b979e).
When selecting any sub menu entry under "Options" the following error is shown:

> "error: null src bitmap in grub_video_bitmap_create_scaled."

There is a "Press any key to continue..." prompt, but Grub continues after a few seconds.

**Additional context**

I found the following hints:

* [#922161](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922161) grub2: null src bitmap error while trying to drop background image
* https://superuser.com/questions/1846090/in-grub2-what-does-error-null-src-bitmap-in-grub-video-bitmap-create-scaled

(Changing the title of this issue and closing grml/grml#214.)
