### ISSUE TITLE
please add binwalk to grml

### ISSUE THREAD

**Issue by Zugschlus** [grml/grml-live#21]
Hi,

binwalk is helpful when unpacking one of those nifty new initrd images with microcode prepended. binwalk tells you how many bytes to skip at the beginning of initrd.img to find the beginning of the actual initrd.

Please consider including binwalk.

Usage example see http://unix.stackexchange.com/questions/163346/why-is-it-that-my-initrd-only-has-one-directory-namely-kernel

Greetings
MArc

**Comment by mika** [comment]
Thanks for the bugreport, grml-full daily ISOs are expected to ship starting by tomorrow's builds.
