### ISSUE TITLE
Reconsider fai conffiles

### ISSUE THREAD

**Issue by zeha** [grml/grml-live#246]
Currently grml-live installs all the FAI config into /etc/grml/fai. They end up being dpkg conffiles.
This is annoying to maintain.

Consider if we can move these files to /usr/share.

Additionally, consider how people are actually using grml-live; do they/we need the .deb at all?

**Comment by mika** [comment]
ACK, let's add a sanity check to make sure that folks how don't use `/usr/share/grml-live/...` or alike but still point to `/etc/grml/fai` get an according failure, then announce the change and migration steps via `debian/NEWS`
