### ISSUE TITLE
using grml-live from the clone

### ISSUE THREAD

**Issue by erickellerek1** [grml/grml-live#26]
I tried to run grml-live script from the cloned location and I think some more env variable are missing in order to make it work in place.

```
root@test:/home/users/test/workspace/grml-live# export GRML_FAI_CONFIG=$(pwd)/etc/grml/fai
root@test:/home/users/test/workspace/grml-live# export SCRIPTS_DIRECTORY=$(pwd)/scripts
root@test:/home/users/test/workspace/grml-live# ./grml-live -s jessie -a amd64 -c GRMLBASE,GRML_FULL,AMD64 -t $(pwd)/templates/
  [x] Configuration file /etc/grml/grml-live.conf can not be read, ignoring

grml-live [***UNRELEASED***]: check your configuration (or use -F to force execution):

  FAI classes:       GRMLBASE,GRML_FULL,AMD64
  Config directory:  /home/users/test/workspace/grml-live/etc/grml/fai
  main directory:    /grml/grml-live
  Chroot target:     /grml/grml-live/grml_chroot
  Build target:      /grml/grml-live/grml_cd
  ISO target:        /grml/grml-live/grml_isos
  Grml name:         grml
  Release name:      grml-live rocks
  Build date:        2017-01-23
  Grml version:      0.0.1
  Debian suite:      jessie
  Architecture:      amd64
  Boot method:       isolinux
  Hybrid method:     isohybrid
  Template files:    /home/users/test/workspace/grml-live/templates/

Is this ok for you? [y/N
```
LIVE_CONF should also be exported? otherwise the configuration cannot be found!
`/etc/grml/grml-live.conf can not be read, ignoring`

In the Readme you mention some dependencies, could you make a list?

**Comment by erickellerek1** [comment]
sudo mk-build-deps --install debian/control installs the dependencies for this project. But the fai-client package should also be listed in the debian/control dependencies.

**Comment by mika** [comment]
Thanks for the hint, I'll provide an update README to clarify LIVE_CONF usage.

"sudo mk-build-deps --install debian/control" doesn't install dependencies, but the *build* dependencies. And inside the Depends of grml-live fai-client is listed. Sadly I'm not aware of a simple command line to install all the packages that are parts of the Depends definition.
