### ISSUE TITLE
find grml ISO on an LV

### ISSUE THREAD

**Issue by Zugschlus** [grml/grml-live#40]
Hi,

grml is still unable to find its ISO on an LV, forcing people who want grml as an option in the grub menu to have /boot on a regular partition. The current release candidate does have the tools on board to find the iso on an LV, since the LVM tools are available in the initrd. When I try booting this way, I end up in an emergency shell after two screenfuls of "unable to open '/dev/sda'". in that emergency shell, i can activate the VG, mount the LV, mount the .iso loopback to /live/medium.
Unfortunately, exiting the rescue shell does not result in a working grml even then.
It would be really nice if the grml release _after_ 2017.05 would be able to boot from an LV.
Greetings
Marc

**Comment by mika** [comment]
I think we had this topic on usenet already and AFAICT it works fine for me with LVM.
(Also it's not a grml-live issue but the bug report should go towards grml-rescueboot if I understand your issue right.)
Closing, until we have more information how to reproduce.
