### ISSUE TITLE
please consider giving information how an iso was built

### ISSUE THREAD

**Issue by Zugschlus** [grml/grml-live#44]
Hi,
to debug something, I would like to be able to build my own grml-full iso that is as close as possible to the official image. Please consider putting information about how an image was built into the iso. Minimum is the combination of fai classes that were used, I would love to have the exact grml-live command line.
Can you please give the combination of fai classes used for grml-{full|small}-2017.05 either in this ticket or in e-mail, so that I can continue with my debugging?
Greetings
Marc

**Comment by mika** [comment]
As written on grml mailing list the following classes are involved:

    DEBORPHAN,GRMLBASE,GRML_FULL,RELEASE,AMD64,IGNORE,SNAPSHOT

**Comment by Zugschlus** [comment]
As we discussed weeks ago in IRC, would it be possible to have that information inside the grml iso? If this is actually already implemented, this issue can be closed now. It would be great if the path in the running grml that tells the user how the running grml was built was mentioned here for reference and the search engines.

**Comment by mika** [comment]
So I implemented this feature via https://github.com/grml/grml-live/commit/9453222c016a82a2c964e174ec01687f88d73d86 for grml-live. Our daily Grml ISOs starting as of tomorrow (2021-07-17) are supposed to include this file, see `/run/live/medium/conf/buildinfo.json` on the running live system then.

Please let me know if that provides everything you're interested in.

FTR: we need to decide yet whether this will be used as-is for our next stable release.
