### ISSUE TITLE
grml-live: 80-initramfs can fail despite d473b06e3427cf602ce623af411d20acf36e5357

### ISSUE THREAD

**Issue by akorn** [grml/grml-live#47]
The patch in commit d473b06e3427cf602ce623af411d20acf36e5357 (which has, unfortunately, not made its way into any release yet) is incomplete.

If `/lib/udev/rules.d/69-lvm-metad.rules` was removed by a prior run of the unpatched script, the patched script will fail to create the placeholder file.

Is there any harm in generating the placeholder unconditionally?

**Comment by mika** [comment]
Thanks, finally took care of it!
