### ISSUE TITLE
Feature Request Clonezilla disk image bionic

### ISSUE THREAD

**Issue by ryanmusante** [grml/grml-live#50]
Included clonezilla image is outdated and is missing key features, i.e. specific ssd drive support. Request future versions of grml include the bionic version by default.

**Comment by mika** [comment]
Thanks for your bug report. Grml uses clonezilla as present in Debian. Is "bionic" referring to a test version of clonezilla? If it's a stable version we could ask for getting a new upstream version into Debian.

**Comment by ryanmusante** [comment]
It is considered testing so as of yet is not ready for stable unfortunately. It seems like it has been a while since the last stable release for clonezilla.

**Comment by mika** [comment]
Ok, then I think it would be best to ask upstream to release a new stable release and as a consequence get a new clonezilla version in Debian as well. There's nothing we (as in Grml) can do about it for now (we try to avoid packaging just for ourselves and are lacking manpower to contribute anything towards upstream here), we're happy to assist in asking for getting a new version into Debian, so feel free if that should be relevant, I'm closing this issue in the meanwhile. Thanks!
