### ISSUE TITLE
suggest adding a QEMU GUI

### ISSUE THREAD

**Issue by mytbk** [grml/grml-live#71]
Thanks all for this great Grml Live with such a small size compared to my Arch Live and the new Arch based SystemRescueCd.
I saw Grml has QEMU in it but without a GUI.
When I designed my Live CD (https://github.com/mytbk/gloriousarch), I thought QEMU can be useful for installing an operating system with KVM directly with an iso image without making a USB stick with the iso. For example, I can install Windows with `sudo qemu-system-x86_64 -enable-kvm -m 4G -cdrom windows.iso -drive /dev/sda,format=raw -boot order=d`.

**Comment by mika** [comment]
Thanks certainly a useful feature, thanks for bringing this to our attention. I've just implemented the change to include the qemu-system-gui Debian package in our grml-full ISOs. The daily ISOs starting as of tomorrow are supposed to include this.
