### ISSUE TITLE
Support qemu-guest-agent out of the box

### ISSUE THREAD

**Issue by jkirk** [grml/grml-live#79]
Already included in grml-full OOTB, consider integrating in grml-small as well (6 - 7 MB). Needs verification.

**Comment by mika** [comment]
FTR: It would add 14MB of additional disk space in grml64-small as of today.

**Comment by mika** [comment]
FTR: qemu-guest-agent is shipped on grml-small as well, we just need to verify this now.

**Comment by mika** [comment]
Works fine as expected
