### ISSUE TITLE
Add radvd

### ISSUE THREAD

**Issue by scaidermern** [grml/grml-live#83]
Please add radvd (IPv6 Router Advertisement Daemon) to grml. radvd is needed to use grml as an IPv6 router. radvd was already part of grml about a decade ago (in [grml_2008.11](http://ml.grml.org/pipermail/bugs-changes/2008-November/000375.html)) but got removed shortly after without any explanation.

**Comment by mika** [comment]
Thanks for your suggestion!

The grml-full flavors of the daily Grml ISOs (see https://grml.org/daily/) are supposed to include radvd as of tomorrow. Please let us know if anything further needs to be done about it.
