### ISSUE TITLE
Decide which boot addons should be still shipped with Grml 2020+ ISOs

### ISSUE THREAD

**Issue by mika** [grml/grml-live#92]
While refreshing the grml-live-grml Debian source package (which builds the grml-live-addons Debian binary package), I noticed that we have several boot addons that are pretty much unmaintained nowadays.

Especially the bsd4grml (4.8MB), balder10.imz (1.2MB, FreeDOS based, see https://www.finnix.org/Balder) + allinone.img (1.5MB, see http://schierlm.users.sourceforge.net/bootdisk/index.html) are among the ones I tend to drop with the upcoming Grml release.

If anyone objects or has further suggestions, please let me/us know!

**Comment by mika** [comment]
Feedback from @schierlm, asking him what's his take on his `allinone.img` usage for Grml:

> probably not... gPXE and Grub are also available separately, so is hdt. And stuff like sbm or plop are no longer needed either, now that every machine can boot from USB...

**Comment by zeha** [comment]
grml-live-grml is not included in the builds anymore. I'll close this.
